# Generated by Django 3.1 on 2020-08-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200804_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
                ('index', models.IntegerField()),
                ('questiontype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.questiontype')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.template')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='TemplateQuestionControlHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25)),
                ('templatequestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.templatequestion')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateQuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('controlchoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.templatequestionchoice')),
                ('templatequestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.templatequestion')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answershort', models.CharField(max_length=250)),
                ('answerbool', models.BooleanField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
                ('templatequestion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.templatequestion')),
                ('templatequestionchoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.templatequestionchoice')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyControlResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlchoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.templatequestionchoice')),
                ('surveyresponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyresponse')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.template'),
        ),
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.user'),
        ),
    ]
