# Generated by Django 3.1 on 2020-08-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200806_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatequestionchoice',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
