# Generated by Django 3.1 on 2020-08-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20200806_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateQuestionControlHeader',
        ),
    ]
