# Generated by Django 3.1 on 2020-08-06 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20200806_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatequestionchoice',
            name='controlchoice',
        ),
        migrations.CreateModel(
            name='TemplateQuestionControlChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('description', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('templatequestionchoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.templatequestionchoice')),
            ],
        ),
    ]
